Default: &defaults
  database: ysd.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: ysd_test.sqlite3
  <<: *defaults

Staging:
  database: ysd_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: ysd_production.sqlite3
  poolsize: 100
  <<: *defaults
